package com.infobeans.ibnextstep.quiz;

import com.infobeans.ibnextstep.common.ApiResponse;
import com.infobeans.ibnextstep.common.PagedResponse;
import com.infobeans.ibnextstep.quiz.dto.*;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.PageRequest;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/api/trainer/quizzes")
@RequiredArgsConstructor
@PreAuthorize("hasRole('TRAINER')")
public class TrainerQuizController {

    private final TrainerQuizService quizService;
    private final QuizAnalyticsService analyticsService;

    @PostMapping("/generate")
    public ApiResponse<Quiz> generate(@Valid @RequestBody GenerateQuizRequest request, Authentication auth) {
        return ApiResponse.success("Quiz generated by AI — review before publishing", quizService.generate(auth.getName(), request));
    }

    @PutMapping("/{id}")
    public ApiResponse<Quiz> update(@PathVariable String id, @Valid @RequestBody UpdateQuizRequest request, Authentication auth) {
        return ApiResponse.success("Quiz updated", quizService.update(auth.getName(), id, request));
    }

    @PutMapping("/{id}/questions/{order}")
    public ApiResponse<Quiz> editQuestion(@PathVariable String id, @PathVariable int order,
                                            @Valid @RequestBody EditQuestionRequest request, Authentication auth) {
        return ApiResponse.success("Question updated", quizService.editQuestion(auth.getName(), id, order, request));
    }

    @DeleteMapping("/{id}/questions/{order}")
    public ApiResponse<Quiz> deleteQuestion(@PathVariable String id, @PathVariable int order, Authentication auth) {
        return ApiResponse.success("Question deleted", quizService.deleteQuestion(auth.getName(), id, order));
    }

    @PostMapping("/{id}/questions")
    public ApiResponse<Quiz> addQuestion(@PathVariable String id, @Valid @RequestBody AddQuestionRequest request, Authentication auth) {
        return ApiResponse.success("Question added", quizService.addQuestion(auth.getName(), id, request));
    }

    @PostMapping("/{id}/questions/{order}/regenerate")
    public ApiResponse<Quiz> regenerateQuestion(@PathVariable String id, @PathVariable int order,
                                                  @RequestBody(required = false) RegenerateQuestionRequest request, Authentication auth) {
        return ApiResponse.success("Question regenerated",
                quizService.regenerateQuestion(auth.getName(), id, order, request != null ? request : new RegenerateQuestionRequest()));
    }

    @PostMapping("/{id}/regenerate")
    public ApiResponse<Quiz> regenerateEntireQuiz(@PathVariable String id, Authentication auth) {
        return ApiResponse.success("Entire quiz regenerated", quizService.regenerateEntireQuiz(auth.getName(), id));
    }

    @DeleteMapping("/{id}")
    public ApiResponse<Void> delete(@PathVariable String id, Authentication auth) {
        quizService.delete(auth.getName(), id);
        return ApiResponse.success("Quiz deleted", null);
    }

    @PostMapping("/{id}/publish")
    public ApiResponse<Quiz> publish(@PathVariable String id, Authentication auth) {
        return ApiResponse.success("Quiz published and students notified", quizService.publish(auth.getName(), id));
    }

    @GetMapping
    public ApiResponse<PagedResponse<Quiz>> list(@RequestParam(defaultValue = "0") int page,
                                                   @RequestParam(defaultValue = "20") int size, Authentication auth) {
        return ApiResponse.success(PagedResponse.from(quizService.list(auth.getName(), PageRequest.of(page, size))));
    }

    @GetMapping("/{id}")
    public ApiResponse<Quiz> getOne(@PathVariable String id, Authentication auth) {
        return ApiResponse.success(quizService.getOne(auth.getName(), id));
    }

    @GetMapping("/{id}/analytics")
    public ApiResponse<QuizAnalyticsResponse> analytics(@PathVariable String id) {
        return ApiResponse.success(analyticsService.analyze(id));
    }

    @GetMapping("/{id}/results")
    public ApiResponse<List<QuizResult>> results(@PathVariable String id) {
        return ApiResponse.success(analyticsService.results(id));
    }
}
